### ISSUE TITLE
Body fails when it contains double quotes.

### ISSUE THREAD

**Issue by bjeanes** [meeDamian/github-release#13] opened 2020-05-18 06:10 UTC
Like https://github.com/meeDamian/github-release/issues/10#issuecomment-562814389, probably need to replace `"` with `\"`. The `sed` filter could probably be moved inline to `toJsonOrNull` to make sure it covers other fields (really just release name).

I know this action is semi-deprecated but I am also stuck on this until the GitHub provided one handles some of the same use cases as your fantastic action.

I'll try to open a PR to fix this but I've worked around it on my end already so unless it comes up again, I _may_ forget, so I thought I'd document it in an issue for the time being.

**Comment by meeDamian** [comment] 2020-06-24 11:39
Hey, it should be fixed by https://github.com/meeDamian/github-release/commit/5264f5bc3f3ab31750ca5e6b416b27acf83e3187, and I'll tag it as `v2.0.2` soon.

**Comment by stm2** [comment] 2020-07-02 11:31
Hey, now it fails when the body contains a backslash.
What worked for me
json_escape () {
          printf '%s' "$1" | python -c 'import json,sys; print(json.dumps(sys.stdin.read()))[1:-1]'
}

The python dependency is the downside.
https://stackoverflow.com/questions/10053678/escaping-characters-in-bash-for-json

Actually, could you use jq itself? 
echo $body | jq -R

**Comment by meeDamian** [comment] 2020-07-02 14:24
@stm2 Can you check if #15 works for you with sth like:

```
uses: meeDamian/github-release@escaping
with:
	…
```

?

**Comment by meeDamian** [comment] 2020-07-03 04:46
Running a [quick test] in my test repo [produced] this [release], looks good to me.

[quick test]: https://github.com/meeDamian/docker-ci/actions/runs/155457574/workflow#L21-L37
[produced]: https://github.com/meeDamian/docker-ci/runs/830942559?check_suite_focus=true#step:5:20
[release]: https://github.com/meeDamian/docker-ci/releases/tag/v10.10.11

**Comment by stm2** [comment] 2020-07-03 09:21
Uhm, I think it works as intended, but not for me. It has been a while or I'm beeing stupid. I'd like to do something like
```
jobs:
  build:
    steps:
      - name: Produce body
        run: |
          text=$(echo -e "Hello!\nWorld!\n")
          echo "set-env name=BODY::$text"
      - name: Create release
        uses: meeDamian/github-release@escaping
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.TAG }}
          name: Pre-Release
          body: |
            ${{ env.BODY }}
```
But BODY only contains the first line. How would I go about producing a multiline body like this?

**Comment by meeDamian** [comment] 2020-07-03 12:20
Could you try with:

```yml
body: >
  ${{ env.BODY }}
```

and 

```yml
body: ${{ env.BODY }}
```

Also, I'd avoid using `echo -e`, or assigning from it w/o quotes (like `text="$(…)"`).

<details>
<summary><code>text=$(echo -e "Hello!\nWorld!\n")</code> 🤔</summary>
<h4>MacOS</h4>

<img width="400" alt="MacOS 2020-07-03 at 20 07 22" src="https://user-images.githubusercontent.com/526657/86468448-04076d00-bd6a-11ea-8e62-bdde8dcd9808.png">

<h4>Debian</h4>

<img width="463" alt="MacOS 2020-07-03 at 20 17 40" src="https://user-images.githubusercontent.com/526657/86468595-4b8df900-bd6a-11ea-8957-1772a5882100.png">


</details>
Maybe try:

```sh
echo "set-env name=BODY::$(printf 'Hello!\nWorld!\n')"
```
or
```sh
text="Hello!
World!"

echo "set-env name=BODY::$text"
```

**Comment by stm2** [comment] 2020-07-04 08:16
You were right about double quotes, of course. I figured out a workaround now from https://github.com/actions/create-release/pull/11. The trick is
```
  text=$(cat CHANGELOG.txt; echo -e '\n\nHello, World!\n')
  text="${text//'%'/'%25'}"
  text="${text//$'\n'/'%0A'}"
  text="${text//$'\r'/'%0D'}"
  echo "set-env name=BODY::$text" 
```

They've also added a way to directly take the body from a file, which I find quite handy: https://github.com/actions/create-release/pull/50

**Comment by meeDamian** [comment] 2020-07-04 08:28
Ok, closing the issue again, as the problem seems to be resolved.

**Closed by meeDamian** 2020-07-04 08:28 UTC
